modLoader="javafml" #mandatory
loaderVersion="[36,)" #mandatory
license="LGPL"

[[mods]] #mandatory
modId="rubidium_toolkit" #mandatory
version="${file.jarVersion}" #mandatory
displayName="Rubidium Toolkit" #mandatory
logoFile="icon.png" #optional
credits="TexTrue" #optional
authors="TexTrueStudio" #optional
description='''
Adds some tools to Rubidium.
'''

[[dependencies.rubidium_toolkit]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[36,)" #mandatory
    ordering="NONE"
    side="BOTH"

[[dependencies.rubidium_toolkit]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"
