modLoader = "javafml" #mandatory
loaderVersion = "[40,)" #mandatory
license = "LGPLv2.1"

[[mods]] #mandatory
modId = "rubidium_toolkit" #mandatory
version = "${version}" #mandatory
displayName = "Rubidium Toolkit" #mandatory
logoFile = "icon.png"
credits = "EnnuiL, Matyrobbrt, TexTrue"
authors = "TexTrueStudio" #optional
description = '''
Add some missing features of Rubidium Extra.
'''

[[dependencies.rubidium_toolkit]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[40,)" #mandatory
ordering = "NONE"
side = "SERVER"

[[dependencies.rubidium_toolkit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.18,)"
ordering = "NONE"
side = "BOTH"