modLoader = "javafml"
loaderVersion = "[36,)"
license = "LGPLv2"

[[mods]]
modId = "rubidium_toolkit"
version = "${version}"
displayName = "Rubidium Toolkit"
displayURL="https://github.com/TexTrueStudio/RubidiumToolkit" #optional
logoFile="icon.png" #optional
credits="TeamDeusVult" #optional
authors="TexTrue, TexTrueStudio, BocchiKessokuTeam" #optional
description = '''

'''

[[dependencies.rubidium_toolkit]]
modId = "forge"
mandatory = true
versionRange = "[36,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rubidium_toolkit]]
modId = "minecraft"
mandatory = true
versionRange = "[1.16.5,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.rubidium_toolkit]]
modId = "rubidium"
mandatory = true
versionRange = "[0.2,)"
ordering = "NONE"
side = "BOTH"
